services:
    saq.rabbitmq.connection:
        class: Saq\RabbitMqQueueBundle\RabbitMq\MqConnection
        arguments: []

    saq.rabbitmq.channel:
        class: Saq\RabbitMqQueueBundle\RabbitMq\MqChannel
        arguments: ["@service_container"]