services:
#    core.example:
#        class: CoreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    saq.rabbitmq.connection.factory:
        class: Saq\RabbitMqQueueBundle\RabbitMq\MqConnectionFactory
        arguments: []